[package]
name = "skim"
version = "0.5.5"
authors = ["Zhang Jinzhou <lotabout@gmail.com>"]
description = "Fuzzy Finder in rust!"
documentation = "https://github.com/lotabout/skim"
homepage = "https://github.com/lotabout/skim"
repository = "https://github.com/lotabout/skim"
readme  = "README.md"
keywords = ["fuzzy", "menu", "util"]
license = "MIT"
edition = "2018"

[lib]
name = "skim"
path = "src/lib.rs"

[[bin]]
name = "sk"
path = "src/main.rs"


[dependencies]
nix = "0.11.0"
regex = "0.2"
lazy_static = "0.2.8"
shlex = "0.1.1"
unicode-width = "0.1.4"
log = "0.3.8"
env_logger = "0.4.3"
time = "0.1.38"
clap = "2.26.2"
tuikit = { git = "https://github.com/lotabout/tuikit.git" }
vte = "0.3.3"
skiplist = "0.2.10"
fuzzy-matcher = "0.2.0"
rayon = "1.0.3"

[features]
default = []

[profile.release]
lto = true
debug = false
